--- #YAML:1.0
name:                Business-Hours
version:             0.09
abstract:            
license:             ~
author:              
    - Jesse Vincent (jesse@cpan.org)
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Set::IntSpan:                  1.12
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
